### ISSUE TITLE
Clicking on username takes you to the person's github profile.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-20-LeaderBoard-Frontend#23]
Eg. When I click on ```dummy-username```, it should redirect me to ```http://www.github.com/dummy-username``` in a new tab.

**Comment by sarthakm21** [comment]
claim

**Comment by harsh-797** [comment]
i want to resolve this issue

**Comment by zerefwayne** [comment]
@sarthakm21 Assigned to you.

**Comment by JLodha** [comment]
claim

**Comment by infern018** [comment]
claim

**Comment by sggts04** [comment]
Can I take this? Its been 2 days

**Comment by ananya-mohanty** [comment]
Can I work on this?

**Comment by JLodha** [comment]
I want to work on this.
It's been 2 days

**Comment by thesmallstar** [comment]
@JLodha  go ahead.

**Comment by thesmallstar** [comment]
@harsh-797 do you want to work on this?

**Comment by JLodha** [comment]
Sir i wanr to work

**Comment by thesmallstar** [comment]
Actually he commented first 😅

**Comment by harsh-797** [comment]
Yes sir i want to try

**Comment by zerefwayne** [comment]
@harsh-797 Assigned to you.

**Comment by prince-7** [comment]
Sir, can i claim this issue

**Comment by JLodha** [comment]
Sir looks like harsh is not able to solve the conflicts.
I want to work on this so please assign me this issue

**Comment by garvitchittora** [comment]
claim

**Comment by blaze-assault** [comment]
Claim
