### ISSUE TITLE
Integrate bootstrap CSS in this project.

### ISSUE THREAD

**Issue by zerefwayne** [opencodeiiita/Opencode-20-LeaderBoard-Frontend#24]
Instructions:

1.  Create a separate folder with the name ```css``` in the root directory.
2. Download all bootstrap CSS files from the official website.
3. Add bootstrap in the index.html file.

**Comment by sarthakm21** [comment]
claim

**Comment by zerefwayne** [comment]
@sarthakm21 Go ahead.

**Comment by zerefwayne** [comment]
@sarthakm21 If possible, please send a PR today itself so we can move forward with the project quickly.
