### ISSUE TITLE
Add a new Page that display all Pr and issue link solved by user 

### ISSUE THREAD

**Issue by thesmallstar** [opencodeiiita/Opencode-20-LeaderBoard-Frontend#30]
HInts:
1. Study the code you will find an API where you can get these details.
2. The username will be passed as a parameter, as GET Request 
i.e example.com/?q=username
3. Design the entire search page. 
4. The issue link might be broken( you can ignore issue link)

**Comment by untrulynoxiusmj** [comment]
claim

**Comment by JLodha** [comment]
claim

**Comment by untrulynoxiusmj** [comment]
https://untrulynoxiusmj.github.io/pages/search.html

sir please check this link 
i have added the functionality on my repo
tell me if everything's correct
So i can design it and make the pr

**Comment by thesmallstar** [comment]
Two things:  
1. You need to display all of them as a link and not text.
2.  issue links are not added. 
You are on the right path though ;)

**Comment by untrulynoxiusmj** [comment]
sir, i am not using concept of GET request

**Comment by untrulynoxiusmj** [comment]
is it fine ?

**Comment by thesmallstar** [comment]
if a user visits the link: 
https://opencodeiiita.github.io/Opencode-20-LeaderBoard-Frontend/search.html/?q=username
fil the search box with the username by default(searched)

**Comment by untrulynoxiusmj** [comment]
ok sir
