### ISSUE TITLE
Add navbar to search page and give the table a similar look as leaderboard table

### ISSUE THREAD

**Issue by sggts04** [opencodeiiita/Opencode-20-LeaderBoard-Frontend#43]
Currently the search page doesn't have the same feel as the main page, the navbar needs to be added to it and its table needs a similar look as the main page's table.

**Comment by sggts04** [comment]
Can I work on this?

**Comment by thesmallstar** [comment]
Not required currently, the nav bar in home page is not yet in its final form. 
And having two different nav bars don't make  any sense.
