### ISSUE TITLE
Display repository name of  issue solved by user and displaying (pull number and issue number) instead of "Link" in table in search page

### ISSUE THREAD

**Issue by untrulynoxiusmj** [opencodeiiita/Opencode-20-LeaderBoard-Frontend#53]

**Comment by thesmallstar** [comment]
Haha! nice try xD 
How about, make the issue a complete title, and PR the way you suggested. 
You can  proceed.

**Comment by untrulynoxiusmj** [comment]
sir,  https://fierce-everglades-19959.herokuapp.com/getData/  doesn't contain info about issue title.
