### ISSUE TITLE
Clicking on user points in  home page takes you to detailed description of user displyed in search page

### ISSUE THREAD

**Issue by untrulynoxiusmj** [opencodeiiita/Opencode-20-LeaderBoard-Frontend#54]

**Comment by thesmallstar** [comment]
it has to take to the github profile, there is already a issue on this.

**Comment by untrulynoxiusmj** [comment]
clicking on user points

**Comment by untrulynoxiusmj** [comment]
username takes github profile
userpoints to search page

**Comment by thesmallstar** [comment]
Rather a add a new table column and choose an appropriate icon for this.

**Comment by thesmallstar** [comment]
Make sure the end result of this should be what happens when we  click the icon, should be what it shows when we search for the person.

**Comment by untrulynoxiusmj** [comment]
ok sir

**Comment by zerefwayne** [comment]
@untrulynoxiusmj Updates?
