### ISSUE TITLE
Make leaderboard responsive for all screen sizes

### ISSUE THREAD

**Issue by tushparte** [opencodeiiita/Opencode-20-LeaderBoard-Frontend#64]
![379A58FF-835B-4A08-9980-61A1FF5DB329](https://user-images.githubusercontent.com/43264385/72909439-05655000-3d5d-11ea-8b51-e1434e476e77.png)

There should not be bugs like this

**Comment by sggts04** [comment]
claim

**Comment by tushparte** [comment]
assigned @sggts04

**Comment by pradhuman1** [comment]
claim
