### ISSUE TITLE
Add Particiapnt photo in table 

### ISSUE THREAD

**Issue by thesmallstar** [opencodeiiita/Opencode-20-LeaderBoard-Frontend#9]
the get request also has participant logo URL,  add participant image before name

**Comment by Mukul-M** [comment]
can i work on this issue

**Comment by thesmallstar** [comment]
yes

**Comment by CadencePrestissimo** [comment]
@opencodebot claim

**Comment by Piyush4064** [comment]
can I work on this?

**Comment by thesmallstar** [comment]
@Mukul-M  updates?

**Comment by JLodha** [comment]
Claim

**Comment by thesmallstar** [comment]
@pavikachaudhary  assigned to you.

**Comment by thesmallstar** [comment]
@pavikachaudhary  are you working on this?

**Comment by CadencePrestissimo** [comment]
yes sir

**Comment by JLodha** [comment]
Sir it's been 2 days
Can i work on this?

**Comment by zerefwayne** [comment]
@JLodha You can work on this.

**Comment by JLodha** [comment]
Ok sir.
> @JLodha You can work on this.

**Comment by JLodha** [comment]
Sir i am facing problem in fetching the link for image of the participant. 
Can you help me with this?
Thanks

**Comment by thesmallstar** [comment]
It is already present In the data received with the API call. 
Try loading the API link in browser, you will get the rest.

**Comment by JLodha** [comment]
Thank you
Please have a look at the PR
> It is already present In the data received with the API call.
> Try loading the API link in browser, you will get the rest.
